In [16]:
import numpy as np

In [17]:
# Given Data
x = np.array([1.0, 1.1, 1.3, 1.5, 1.9, 2.1])
y = np.array([1.84, 1.96, 2.21, 2.45, 2.94, 3.18])

In [18]:
# Utilize the singular value decomposition method to find the linear least squares polynomial of degree 2

X = np.vstack([np.ones_like(x), x, x**2]).T


U, S, Vt = np.linalg.svd(X, full_matrices=False)
S_inv = np.diag(1 / S)


b = Vt.T @ S_inv @ U.T @ y

print("Coefficients (a0, a1, a2):", b)

Coefficients (a0, a1, a2): [ 0.59658071  1.25329314 -0.01085343]


In [19]:
U

array([[-0.20333922,  0.55082788,  0.55402391],
       [-0.23165137,  0.49843044,  0.18561763],
       [-0.29463216,  0.36925792, -0.33774238],
       [-0.36608827,  0.20758188, -0.57649901],
       [-0.53442645, -0.21328077, -0.20020211],
       [-0.63130852, -0.47246737,  0.41485141]])

In [20]:
S

array([7.84412681, 1.22378978, 0.07009428])

In [21]:
Vt

array([[-0.28829799, -0.47570216, -0.83101848],
       [ 0.76839176,  0.40292422, -0.49721845],
       [ 0.57136536, -0.78189483,  0.24936338]])

In [22]:
S_inv

array([[ 0.12748392,  0.        ,  0.        ],
       [ 0.        ,  0.81713381,  0.        ],
       [ 0.        ,  0.        , 14.2664987 ]])

In [23]:
# Utilize the singular value decomposition method to find the linear least squares polynomial of degree 3

X = np.vstack([np.ones_like(x), x, x**2, x**3]).T


U, S, Vt = np.linalg.svd(X, full_matrices=False)
S_inv = np.diag(1 / S)


b = Vt.T @ S_inv @ U.T @ y

print("Coefficients (a0, a1, a2, a3):", b)

Coefficients (a0, a1, a2, a3): [ 0.62901928  1.1850098   0.03533252 -0.01004723]


In [24]:
U

array([[-0.11608603,  0.51462363, -0.5691128 , -0.43786621],
       [-0.14361447,  0.50358556, -0.2663253 ,  0.18450951],
       [-0.21244104,  0.44812067,  0.23847487,  0.48499575],
       [-0.3019628 ,  0.33992294,  0.54961907,  0.03858126],
       [-0.55430303, -0.07410078,  0.30634976, -0.63677614],
       [-0.72272702, -0.39964163, -0.39035867,  0.36336784]])

In [25]:
S

array([1.45068078e+01, 2.08490854e+00, 1.98760092e-01, 8.68328133e-03])

In [26]:
Vt

array([[-0.14139116, -0.24637274, -0.44920712, -0.84706669],
       [ 0.63912175,  0.56643737,  0.2955474 , -0.42816332],
       [-0.66086235,  0.17451522,  0.66784011, -0.29460989],
       [-0.36714151,  0.76680741, -0.51463997,  0.11117195]])

In [27]:
S_inv

array([[6.89331529e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 4.79637347e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.03119107e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.15163838e+02]])